version: '3.8'

services:
  db: 
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=PENDAFTARAN
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - "./db/data/mysql:/var/lib/mysql"

  www:
    image: php:apache
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8001:80
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8002:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306